const {
  PORT_NO,
  CONNECTION_URL_PATH,
  JWT_SECRET_CODE,
  SENDER_EMAIL_PATH,
  EMAIL_PASSWORD_PASS,
  AWS_ACCESS_KEY_VALUE,
  AWS_SECRECT_ACCESS_KEY_VALUE,
  AWS_BUCKET_NAME_IS,
  AWS_REGION_AREA
} = process.env;

module.exports = {
  port: PORT_NO,
  connectionURL: CONNECTION_URL_PATH,
  jwtSecret: JWT_SECRET_CODE,
  senderEmail: SENDER_EMAIL_PATH,
  emailPassword: EMAIL_PASSWORD_PASS,
  awsAccessKey: AWS_ACCESS_KEY_VALUE,
  awsSecrectAccessKey: AWS_SECRECT_ACCESS_KEY_VALUE,
  awsBusketName: AWS_BUCKET_NAME_IS,
  awsRegion: AWS_REGION_AREA,
};
